NOT_COLLECTED = "XXX_NOT_COLLECTED_XXX"

PLACEHOLDERS = {"", "0", "00000", "null", "none", "na", "n/a", "xxx_not_collected_xxx"}

REPLACE_MAPPING_COLS = [
    "ACCOUNT_LAST_NAME", "ACCOUNT_FIRST_NAME", "ACCOUNT_MIDDLE_NAME", "DATE_OPENED",
    "ACCOUNT_HOLDER_DOB", "ACCOUNT_TYPE", "CARD_TYPE", "ACCOUNT_ADDRESS", "ADDRESS_CITY",
    "ADDRESS_PROVINCE", "ADDRESS_COUNTRY", "POSTAL_CODE", "PHONE_NUMBER", "EMAIL_ADDRESS",
    "ID_TYPE", "ID_NUMBER", "ID_COUNTRY", "NATIONALITY", "ISSUING_FI", "CARD_PROGRAM",
    "CARD_STATUS", "SECONDARY_CARD_TYPE",
]

CMS_UPDATE_COLS = ["CARD_NUMBER", "ACCOUNT_TYPE", "CARD_TYPE", "CARD_PROGRAM", "CARD_STATUS"]

# Columns for the CMS sheet added to the review workbook download -- deliberately
# a subset of CMS_UPDATE_COLS (no CARD_NUMBER). Kept separate from CMS_UPDATE_COLS
# because the live CMS upload/merge still requires the full 5-column set.
CMS_SHEET_COLS = ["ACCOUNT_TYPE", "CARD_TYPE", "CARD_PROGRAM", "CARD_STATUS"]

RAW_REQUIRED_COLS = list(dict.fromkeys(["ACCOUNT_NUMBER", *REPLACE_MAPPING_COLS, *CMS_UPDATE_COLS]))
